<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="monitorrepository" nsURI="http://palladiosimulator.org/SimuLizar/MonitorRepository/1.0"
    nsPrefix="monitorrepository">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="edp2" value="../../../plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint"/>
    <details key="entity" value="../../../plugin/de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity"/>
    <details key="identifier" value="../../../plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#/"/>
    <details key="metricspec" value="../../../plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MonitorRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class representing the monitor repository model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" upperBound="-1"
        eType="#//Monitor" containment="true" eOpposite="#//Monitor/monitorRepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A performance measurement for a pcm element (type level)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurementSpecifications"
        lowerBound="1" upperBound="-1" eType="#//MeasurementSpecification" containment="true"
        eOpposite="#//MeasurementSpecification/monitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuringPoint" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/MeasuringPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorRepository" lowerBound="1"
        eType="#//MonitorRepository" eOpposite="#//MonitorRepository/monitors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementSpecification" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A measurement specification for a pcm element including the performance metric and the statistical charaterization."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="temporalRestriction" lowerBound="1"
        eType="#//TemporalCharacterization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statisticalCharacterization"
        lowerBound="1" eType="#//StatisticalCharacterizationEnum" defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metricDescription" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//MetricDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitor" lowerBound="1"
        eType="#//Monitor" eOpposite="#//Monitor/measurementSpecifications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" defaultValueLiteral="" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="self.monitor.entityName + ': ' + self.statisticalCharacterization.toString() + ' of ' + self.temporalRestriction.oclAsType(ecore::EObject).eClass().name"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalCharacterization" abstract="true"
      eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for the intervall of the measurement specification."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intervall" eSuperTypes="#//TemporalCharacterization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Simple intervall."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervall" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayedIntervall" eSuperTypes="#//Intervall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Simple intervall starting after a specified delay."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeFrame" eSuperTypes="#//TemporalCharacterization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Interval representing a strict time intervall with start and end times."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stop" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatisticalCharacterizationEnum">
    <eLiterals name="None"/>
    <eLiterals name="Median" value="1"/>
    <eLiterals name="ArithmeticMean" value="2"/>
    <eLiterals name="GeometricMean" value="3"/>
    <eLiterals name="HarmonicMean" value="4"/>
  </eClassifiers>
</ecore:EPackage>
