<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="violationstrategymappings" nsURI="http://simulizar.palladiosimulator.org/lafore/violationstrategymappings/1.0"
    nsPrefix="violationstrategymappings">
  <eClassifiers xsi:type="ecore:EClass" name="ViolationStrategyMapping" eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="violation" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.simulizar.lafore.violations/model/violations.ecore#//ViolationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategies" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.simulizar.lafore.strategies/model/strategies.ecore#//StrategyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategyPriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViolationStrategyMappingRepository"
      eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vsmappings" upperBound="-1"
        eType="#//ViolationStrategyMapping" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
