<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pms" nsURI="http://simulizar.palladiosimulator.org/PalladioMonitoringSpecification/1.0"
    nsPrefix="pms">
  <eClassifiers xsi:type="ecore:EClass" name="PMSModel" eSuperTypes="#//UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class representing the pms model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performanceMeasurements"
        upperBound="-1" eType="#//PerformanceMeasurement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceMeasurement" eSuperTypes="#//UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A performance measurement for a pcm element (type level)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurementSpecification"
        lowerBound="1" upperBound="-1" eType="#//MeasurementSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuringPoint" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/MeasuringPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementSpecification" eSuperTypes="#//UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A measurement specification for a pcm element including the performance metric and the statistical charaterization."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="temporalRestriction" lowerBound="1"
        eType="#//TemporalCharacterization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="performanceMetric" lowerBound="1"
        eType="#//PerformanceMetricEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statisticalCharacterization"
        lowerBound="1" eType="#//StatisticalCharacterizationEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalCharacterization" abstract="true"
      eSuperTypes="#//UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for the intervall of the measurement specification."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intervall" eSuperTypes="#//TemporalCharacterization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Simple intervall."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervall" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayedIntervall" eSuperTypes="#//Intervall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Simple intervall starting after a specified delay."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeFrame" eSuperTypes="#//TemporalCharacterization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Interval representing a strict time intervall with start and end times."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stop" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PerformanceMetricEnum">
    <eLiterals name="WaitingTime"/>
    <eLiterals name="ResponseTime" value="1"/>
    <eLiterals name="Utilization" value="2"/>
    <eLiterals name="ArrivalRate" value="3"/>
    <eLiterals name="Throughput" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatisticalCharacterizationEnum">
    <eLiterals name="None"/>
    <eLiterals name="Median" value="1"/>
    <eLiterals name="ArithmeticMean" value="2"/>
    <eLiterals name="GeometricMean" value="3"/>
    <eLiterals name="HarmonicMean" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Superclass of all classes to store unique identifier."/>
    </eAnnotations>
    <eOperations name="createAndSetGuid">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(this.getGuid() == null) this.setGuid(org.eclipse.emf.ecore.util.EcoreUtil.generateUUID());"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
