/* Generated By:JavaCC: Do not edit this line. ConditionExpParserConstants.java */
package de.mdelab.eurema.interpreter.condition;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConditionExpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int NOT_EQUALS = 12;
  /** RegularExpression Id. */
  int GREATER = 13;
  /** RegularExpression Id. */
  int SMALLER = 14;
  /** RegularExpression Id. */
  int GREATER_EQUALS = 15;
  /** RegularExpression Id. */
  int SMALLER_EQUALS = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int MULTIPLY = 19;
  /** RegularExpression Id. */
  int DIVIDE = 20;
  /** RegularExpression Id. */
  int CURRENT_TIME = 21;
  /** RegularExpression Id. */
  int SEPARATOR = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int C_SINCE = 24;
  /** RegularExpression Id. */
  int T_WHEN = 25;
  /** RegularExpression Id. */
  int START_PARAM = 26;
  /** RegularExpression Id. */
  int PARAM = 27;
  /** RegularExpression Id. */
  int END_PARAM = 28;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_METHOD = 1;
  /** Lexical state. */
  int END_METHOD = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"NOT\"",
    "\"AND\"",
    "\"OR\"",
    "\"ELSE\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"CURRENT_TIME\"",
    "\"::\"",
    "<NUMBER>",
    "\"C_SINCE\"",
    "\"T_WHEN\"",
    "<START_PARAM>",
    "<PARAM>",
    "<END_PARAM>",
  };

}
