<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reconfigurationrule" nsURI="http://palladiosimulator.org/simulizar/reconfigurationrule/1.0"
    nsPrefix="reconf">
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationRuleSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//ReconfigurationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Priority of the reconfiguration rule represented as Integer. Values from 0 to n are the priority in a ruleset which determine the order of which a reconfiguration rule is executed. Lower values are higher priority, earlier execution. The value -1 means unspecified priority and is equal to the latest execution within the ruleset. The order in which multiple rules with unspecified priority are executed is non-deterministic."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionCheck" lowerBound="1"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//ModelTransformation">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationAction" lowerBound="1"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//ModelTransformation">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTransformation" abstract="true">
    <eTypeParameters name="ExecutableTransformationElement">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTransformation">
      <eGenericType eTypeParameter="#//ModelTransformation/ExecutableTransformationElement"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
