/**
 *
 * $Id$
 */
package org.palladiosimulator.simulizar.reconfigurationrule.validation;

import org.eclipse.emf.common.util.EList;
import org.palladiosimulator.simulizar.reconfigurationrule.Strategy;

/**
 * A sample validator interface for {@link org.palladiosimulator.simulizar.reconfigurationrule.Reconfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReconfigurationValidator {
	boolean validate();

	boolean validateStrategies(EList<Strategy> value);
}
