<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prm" nsURI="http://simulizar.palladiosimulator.org/PalladioRuntimeMonitoring/1.0"
    nsPrefix="prm">
  <eClassifiers xsi:type="ecore:EClass" name="PRMModel" eSuperTypes="#//UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class representing the prm model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmModelElementMeasurements"
        upperBound="-1" eType="#//PCMModelElementMeasurement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCMModelElementMeasurement" eSuperTypes="#//UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Measurement for a pcm model element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcmModelElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorRepository" eType="ecore:EClass ../../org.palladiosimulator.simulizar.monitorrepository/model/monitorrepository.ecore#//MonitorRepository"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measurementValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Superclass of all classes to store unique identifier."/>
    </eAnnotations>
    <eOperations name="createAndSetGuid">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(this.getGuid() == null) this.setGuid(org.eclipse.emf.ecore.util.EcoreUtil.generateUUID());"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceContainerMeasurement" eSuperTypes="#//PCMModelElementMeasurement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Measurement for a resource of a resource container."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingResourceType"
        eType="ecore:EClass platform:/plugin/de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourcetype/ProcessingResourceType"/>
  </eClassifiers>
</ecore:EPackage>
