<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulizarmeasuringpoint" nsURI="http://palladiosimulator.org/simulizar/measuringpoint"
    nsPrefix="simulizarmeasuringpoint">
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationMeasuringPoint" eSuperTypes="platform:/plugin/org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/StringMeasuringPoint"/>
</ecore:EPackage>
