<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="servicelevelobjective" nsURI="http://palladiosimulator.org/ServiceLevelObjective/1.0"
    nsPrefix="slo">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceLevelObjectiveRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicelevelobjectives"
        upperBound="-1" eType="#//ServiceLevelObjective" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceLevelObjective" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerThreshold" eType="#//Threshold"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperThreshold" eType="#//Threshold"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Threshold" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thresholdLimit" eType="#//JSMeasure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardThreshold" eSuperTypes="#//Threshold"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinearFuzzyThreshold" eSuperTypes="#//Threshold">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="softLimit" eType="#//JSMeasure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JSMeasure" instanceClassName="javax.measure.Measure">
    <eTypeParameters name="V"/>
    <eTypeParameters name="Q">
      <eBounds eClassifier="#//JSQuantity"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JSQuantity" instanceClassName="javax.measure.quantity.Quantity"/>
</ecore:EPackage>
