<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="action" nsURI="http://simulizar.palladiosimulator.org/Actions/1.1"
    nsPrefix="org.palladiosimulator">
  <eSubpackages name="core" nsURI="http://simulizar.palladiosimulator.org/Actions/Core/1.1"
      nsPrefix="org.palladiosimulator.action">
    <eClassifiers xsi:type="ecore:EClass" name="AdaptationBehaviorRepository" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
          eType="#//core/AdaptationBehavior" containment="true" eOpposite="#//core/AdaptationBehavior/repository"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includedRepositories"
          upperBound="-1" eType="#//core/AdaptationBehaviorRepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAdaptationBehavior" abstract="true"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="adaptationSteps" lowerBound="1"
          upperBound="-1" eType="#//core/AdaptationStep" containment="true" eOpposite="#//core/AdaptationStep/adaptationBehavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdaptationBehavior" eSuperTypes="#//core/AbstractAdaptationBehavior">
      <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).addControllerCallVariableUsages(controllerCallsVariableUsages).build().doSwitch(this).getExecutionResultAsBoolean();&#xD;&#xA;"/>
          <details key="documentation" value="Executes this AdaptationBehavior for the given RoleSet and with the given VariableUsages.&#xD;&#xA;As no ExecutionContext is passed, this behavior will be processed by the main thread, i.e. by the underlying ReconfigurationProcess."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" lowerBound="1" eType="#//instance/RoleSet"/>
        <eParameters name="controllerCallsVariableUsages" lowerBound="1" eType="#//parameter/ControllerCallInputVariableUsageCollection"/>
      </eOperations>
      <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).addControllerCallVariableUsages(controllerCallsVariableUsages).addExecutionContext(executionContext).build().doSwitch(this).getExecutionResultAsBoolean();&#xD;&#xA;"/>
          <details key="documentation" value="Executes this AdaptationBehavior for the given RoleSet and with the given VariableUsages.&#xD;&#xA;Note that the behavior is synchronously executed by the process that is associated with the given context."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" lowerBound="1" eType="#//instance/RoleSet"/>
        <eParameters name="controllerCallsVariableUsages" lowerBound="1" eType="#//parameter/ControllerCallInputVariableUsageCollection"/>
        <eParameters name="executionContext" eType="#//context/ExecutionContext"/>
      </eOperations>
      <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).build().doSwitch(this).getExecutionResultAsBoolean();"/>
          <details key="documentation" value="Executes this AdaptationBehavior for the given RoleSet.&#xD;&#xA;As no ExecutionContext is passed, this behavior will be processed by the main thread, i.e. by the underlying ReconfigurationProcess."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" lowerBound="1" eType="#//instance/RoleSet"/>
      </eOperations>
      <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).addExecutionContext(executionContext).build().doSwitch(this).getExecutionResultAsBoolean();&#xD;&#xA;"/>
          <details key="documentation" value="Executes this AdaptationBehavior for the given RoleSet and with the given VariableUsages.&#xD;&#xA;Note that the behavior is synchronously executed by the process that is associated with the given context."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" lowerBound="1" eType="#//instance/RoleSet"/>
        <eParameters name="executionContext" eType="#//context/ExecutionContext"/>
      </eOperations>
      <eOperations name="executeAsync" lowerBound="1" eType="#//context/ExecutionContext">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).addControllerCallVariableUsages(controllerCallsVariableUsages).isAsync().build().doSwitch(this).getContext().get();&#xD;&#xA;"/>
          <details key="documentation" value="Triggers the asynchronous execution of this AdaptationBehavior for the given RoleSet and VariableUsages.&#xD;&#xA;The ExecutionContext of the executing process, which is created before the async process is spawned, is returned.&#xD;&#xA;It should be passed to synchronous adaptation behavior executions that are done within."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" lowerBound="1" eType="#//instance/RoleSet"/>
        <eParameters name="controllerCallsVariableUsages" lowerBound="1" eType="#//parameter/ControllerCallInputVariableUsageCollection"/>
      </eOperations>
      <eOperations name="executeAsync" eType="#//context/ExecutionContext">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).isAsync(asyncExecutionContext).addControllerCallVariableUsages(controllerCallsVariableUsages).build().doSwitch(this);&#xD;&#xA;return asyncExecutionContext;&#xD;&#xA;"/>
          <details key="documentation" value="Triggers the asynchronous execution of this AdaptationBehavior for the given RoleSet and VariableUsages in the given ExecutionContext.&#xD;&#xA;To conform to ome overloaded versions of this method, this context  is also returned.&#xD;&#xA;It should be passed to synchronous adaptation behavior executions that are done within."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" eType="#//instance/RoleSet"/>
        <eParameters name="controllerCallsVariableUsages" lowerBound="1" eType="#//parameter/ControllerCallInputVariableUsageCollection"/>
        <eParameters name="asyncExecutionContext" eType="#//context/ExecutionContext"/>
      </eOperations>
      <eOperations name="executeAsync" lowerBound="1" eType="#//context/ExecutionContext">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).isAsync().build().doSwitch(this).getContext().get();"/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" lowerBound="1" eType="#//instance/RoleSet"/>
      </eOperations>
      <eOperations name="executeAsync" eType="#//context/ExecutionContext">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="org.palladiosimulator.simulizar.action.interpreter.ActionRuntimeState.getInterpreterBuilder(affectedRoleSet, getRepository()).isAsync(asyncExecutionContext).build().doSwitch(this);&#xD;&#xA;return asyncExecutionContext;&#xD;&#xA;"/>
          <details key="documentation" value="Triggers the asynchronous execution of this AdaptationBehavior for the given RoleSet in the given ExecutionContext.&#xD;&#xA;To conform to ome overloaded versions of this method, this context  is also returned.&#xD;&#xA;It should be passed to synchronous adaptation behavior executions that are done within."/>
        </eAnnotations>
        <eParameters name="affectedRoleSet" eType="#//instance/RoleSet"/>
        <eParameters name="asyncExecutionContext" eType="#//context/ExecutionContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="involvedRoles" lowerBound="1"
          upperBound="-1" eType="#//core/RoleType" containment="true" eOpposite="#//core/RoleType/action"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transientStateProfile"
          eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Profile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//core/AdaptationBehaviorRepository"
          eOpposite="#//core/AdaptationBehaviorRepository/actions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedAdaptationBehavior" eSuperTypes="#//core/AbstractAdaptationBehavior">
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardedTransition" eType="#//core/GuardedTransition"
          eOpposite="#//core/GuardedTransition/nestedAdaptationBehavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdaptationStep" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="adaptationBehavior" eType="#//core/AbstractAdaptationBehavior"
          eOpposite="#//core/AbstractAdaptationBehavior/adaptationSteps"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateTransformingStep" eSuperTypes="#//core/AdaptationStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnactAdaptationStep" eSuperTypes="#//core/AdaptationStep">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptationStepURI" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceDemandingStep" eSuperTypes="#//core/AdaptationStep">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="controllerCompletionURI"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controllerCalls" lowerBound="1"
          upperBound="-1" eType="#//core/ControllerCall" containment="true" eOpposite="#//core/ControllerCall/resourceDemandingStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GuardedStep" eSuperTypes="#//core/AdaptationStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardedTransitions" upperBound="-1"
          eType="#//core/GuardedTransition" containment="true" eOpposite="#//core/GuardedTransition/guardedStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GuardedTransition" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardedStep" eType="#//core/GuardedStep"
          eOpposite="#//core/GuardedStep/guardedTransitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nestedAdaptationBehavior"
          eType="#//core/NestedAdaptationBehavior" containment="true" eOpposite="#//core/NestedAdaptationBehavior/guardedTransition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoleType" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//core/AdaptationBehavior"
          eOpposite="#//core/AdaptationBehavior/involvedRoles"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControllerCall" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/BasicComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledSignature" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceDemandingStep"
          eType="#//core/ResourceDemandingStep" eOpposite="#//core/ResourceDemandingStep/controllerCalls"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="mapping" nsURI="http://simulizar.palladiosimulator.org/Actions/Mapping/1.1"
      nsPrefix="org.palladiosimulator.action">
    <eClassifiers xsi:type="ecore:EClass" name="Mapping" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controllerMappings" lowerBound="1"
          upperBound="-1" eType="#//mapping/ControllerMapping" containment="true"
          eOpposite="#//mapping/ControllerMapping/mapping"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControllerMapping" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappedCall" lowerBound="1"
          eType="#//core/ControllerCall"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controllerRole" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationProvidedRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" eType="#//mapping/Mapping"
          eOpposite="#//mapping/Mapping/controllerMappings"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="instance" nsURI="http://simulizar.palladiosimulator.org/Actions/Instance/1.1"
      nsPrefix="org.palladiosimulator.action">
    <eClassifiers xsi:type="ecore:EClass" name="RoleSet" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1"
          upperBound="-1" eType="#//instance/Role" containment="true" eOpposite="#//instance/Role/roleSet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="roleSet" eType="#//instance/RoleSet"
          eOpposite="#//instance/RoleSet/roles"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roleType" lowerBound="1"
          eType="#//core/RoleType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="parameter" nsURI="http://simulizar.palladiosimulator.org/Actions/Parameter/1.1"
      nsPrefix="org.palladiosimulator.action">
    <eClassifiers xsi:type="ecore:EClass" name="ControllerCallInputVariableUsage"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableUsage" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingControllerCall"
          lowerBound="1" eType="#//core/ControllerCall"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containingCollection"
          eType="#//parameter/ControllerCallInputVariableUsageCollection" eOpposite="#//parameter/ControllerCallInputVariableUsageCollection/controllerCallInputVariableUsages"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControllerCallInputVariableUsageCollection"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controllerCallInputVariableUsages"
          upperBound="-1" eType="#//parameter/ControllerCallInputVariableUsage" containment="true"
          eOpposite="#//parameter/ControllerCallInputVariableUsage/containingCollection"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="context" nsURI="http://simulizar.palladiosimulator.org/Actions/Context/1.1"
      nsPrefix="org.palladiosimulator.action">
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionContext" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
  </eSubpackages>
</ecore:EPackage>
